const genelkulturData = {
    easy: [
        { q: "Türkiye'nin başkenti neresidir?", options: ["İstanbul", "Ankara", "İzmir", "Antalya"], a: "Ankara" },
        { q: "Gökkuşağı kaç renkten oluşur?", options: ["5", "6", "7", "8"], a: "7" },
        { q: "Dünyanın uydusu hangisidir?", options: ["Güneş", "Mars", "Ay", "Venüs"], a: "Ay" },
        { q: "Güneş hangi yönden doğar?", options: ["Batı", "Kuzey", "Doğu", "Güney"], a: "Doğu" },
        { q: "İstiklal Marşı'nın yazarı kimdir?", options: ["Ziya Gökalp", "Namık Kemal", "M. Akif Ersoy", "Reşat Nuri"], a: "M. Akif Ersoy" },
        { q: "Üçgenin iç açılarının toplamı kaçtır?", options: ["90", "180", "360", "270"], a: "180" },
        { q: "Ekmek hangi tahıldan yapılır?", options: ["Mısır", "Arpa", "Buğday", "Yulaf"], a: "Buğday" },
        { q: "Bal arıları ne üretir?", options: ["Süt", "Bal", "Peynir", "Reçel"], a: "Bal" },
        { q: "Tavşanlar en çok hangi sebzeyi sever?", options: ["Marul", "Salatalık", "Havuç", "Domates"], a: "Havuç" },
        { q: "Sütün rengi nedir?", options: ["Sarı", "Mavi", "Beyaz", "Yeşil"], a: "Beyaz" },
        { q: "Haftanın ilk günü hangisidir?", options: ["Pazar", "Salı", "Pazartesi", "Cuma"], a: "Pazartesi" },
        { q: "Türkiye'nin en kalabalık şehri?", options: ["Ankara", "İzmir", "İstanbul", "Bursa"], a: "İstanbul" },
        { q: "Hangisi bir mevsim değildir?", options: ["Yaz", "Kış", "Eylül", "İlkbahar"], a: "Eylül" },
        { q: "Uçağı kim uçurur?", options: ["Kaptan", "Pilot", "Şoför", "Makinist"], a: "Pilot" },
        { q: "Dondurma hangi mevsimde daha çok tüketilir?", options: ["Kış", "Güz", "Yaz", "Bahar"], a: "Yaz" },
        { q: "Hangi hayvan 'miyav' der?", options: ["Köpek", "Kedi", "Kuş", "At"], a: "Kedi" },
        { q: "Pamuk Prenses kaç cüceyle yaşar?", options: ["5", "6", "7", "8"], a: "7" },
        { q: "Bir gün kaç saattir?", options: ["12", "24", "48", "60"], a: "24" },
        { q: "Kırmızı ve sarı karışınca hangi renk olur?", options: ["Yeşil", "Mor", "Turuncu", "Mavi"], a: "Turuncu" },
        { q: "Hangisi bir ulaşım aracıdır?", options: ["Televizyon", "Otobüs", "Sandalye", "Masa"], a: "Otobüs" }
    ],
    medium: [
        { q: "Mona Lisa tablosu kime aittir?", options: ["Picasso", "Da Vinci", "Dali", "Van Gogh"], a: "Da Vinci" },
        { q: "Hangi ülke 'Yükselen Güneşin Ülkesi'dir?", options: ["Çin", "Hindistan", "Japonya", "Kore"], a: "Japonya" },
        { q: "Dünyanın en uzun nehri hangisidir?", options: ["Amazon", "Nil", "Mississippi", "Tuna"], a: "Nil" },
        { q: "Eyfel Kulesi hangi şehirdedir?", options: ["Londra", "Roma", "Paris", "Madrid"], a: "Paris" },
        { q: "Sıvı haldeki tek metal hangisidir?", options: ["Altın", "Demir", "Cıva", "Bakır"], a: "Cıva" },
        { q: "Piramitler hangi ülkededir?", options: ["Yunanistan", "Mısır", "Meksika", "İtalya"], a: "Mısır" },
        { q: "Telefonu kim icat etti?", options: ["Edison", "Graham Bell", "Tesla", "Newton"], a: "Graham Bell" },
        { q: "Kızıl Gezegen hangisidir?", options: ["Venüs", "Mars", "Satürn", "Merkür"], a: "Mars" },
        { q: "Brezilya'nın resmi dili nedir?", options: ["İspanyolca", "İngilizce", "Portekizce", "Fransızca"], a: "Portekizce" },
        { q: "Satrancın ana vatanı neresidir?", options: ["Çin", "Mısır", "Hindistan", "İran"], a: "Hindistan" },
        { q: "Hangi organımız kanı pompalar?", options: ["Akciğer", "Böbrek", "Kalp", "Mide"], a: "Kalp" },
        { q: "Yüzölçümü en büyük ülke hangisidir?", options: ["Çin", "ABD", "Rusya", "Kanada"], a: "Rusya" },
        { q: "Sinekli Bakkal romanının yazarı kimdir?", options: ["Reşat Nuri", "Halide Edip", "Yaşar Kemal", "Sabahattin Ali"], a: "Halide Edip" },
        { q: "İlk Türk kadın pilot kimdir?", options: ["Türkan Akyol", "Sabiha Gökçen", "Afet İnan", "Halide Edip"], a: "Sabiha Gökçen" },
        { q: "Titanik hangi yıl batmıştır?", options: ["1910", "1912", "1915", "1920"], a: "1912" },
        { q: "Olimpiyatlar kaç yılda bir yapılır?", options: ["2", "3", "4", "5"], a: "4" },
        { q: "Nobel ödülleri hangi ülkede verilir?", options: ["Almanya", "İsveç", "ABD", "Fransa"], a: "İsveç" },
        { q: "Asya ve Avrupa'yı bağlayan şehir?", options: ["Ankara", "Atina", "İstanbul", "Moskova"], a: "İstanbul" },
        { q: "Fatih Sultan Mehmet İstanbul'u kaç yılında fethetti?", options: ["1071", "1299", "1453", "1517"], a: "1453" },
        { q: "Hangi elementin simgesi 'Au'dur?", options: ["Gümüş", "Bakır", "Altın", "Alüminyum"], a: "Altın" }
    ],
    hard: [
        { q: "Dünyanın en derin noktası neresidir?", options: ["Mariana Çukuru", "Bermuda", "Everest", "Nil"], a: "Mariana Çukuru" },
        { q: "Ütopya kitabının yazarı kimdir?", options: ["Platon", "Thomas More", "Machiavelli", "Hegel"], a: "Thomas More" },
        { q: "Dante'nin ünlü eserinin adı nedir?", options: ["Suç ve Ceza", "Sefiller", "İlahi Komedya", "Faust"], a: "İlahi Komedya" },
        { q: "Hangi elementin simgesi 'W' harfidir?", options: ["Tungsten", "Varyum", "Platin", "Potasyum"], a: "Tungsten" },
        { q: "Nobel Barış Ödülü hangi şehirde verilir?", options: ["Stokholm", "Oslo", "Helsinki", "Kopenhag"], a: "Oslo" },
        { q: "Modern atom teorisinin kurucusu kimdir?", options: ["John Dalton", "Niels Bohr", "Einstein", "Rutherford"], a: "John Dalton" },
        { q: "Altın oran rakamı yaklaşık kaçtır?", options: ["1.414", "1.618", "2.718", "3.141"], a: "1.618" },
        { q: "Don Kişot'un yazarı kimdir?", options: ["Lorca", "Hugo", "Cervantes", "Moliere"], a: "Cervantes" },
        { q: "Aspirinin ham maddesi hangi ağaçtır?", options: ["Meşe", "Söğüt", "Çam", "Gürgen"], a: "Söğüt" },
        { q: "Dünyanın en küçük ülkesi hangisidir?", options: ["Monako", "Vatikan", "Malta", "Andorra"], a: "Vatikan" },
        { q: "İnsan vücudundaki en küçük kemik hangisidir?", options: ["Çekiç", "Örs", "Üzengi", "Kaval"], a: "Üzengi" },
        { q: "Safra nerede üretilir?", options: ["Mide", "Pankreas", "Karaciğer", "Böbrek"], a: "Karaciğer" },
        { q: "I. Dünya Savaşı'nı bitiren antlaşma?", options: ["Versay", "Lozan", "Mondros", "Sevr"], a: "Versay" },
        { q: "Hangi gezegen ters yönde döner?", options: ["Mars", "Venüs", "Neptün", "Satürn"], a: "Venüs" },
        { q: "İlk bilgisayarın adı nedir?", options: ["Altair", "Eniac", "Deep Blue", "Macintosh"], a: "Eniac" },
        { q: "Divan-ı Lügati't-Türk yazarı?", options: ["Mevlana", "Yunus Emre", "Kaşgarlı Mahmut", "Hacı Bektaş"], a: "Kaşgarlı Mahmut" },
        { q: "Periyodik tabloda 1 numaralı element?", options: ["Helyum", "Oksijen", "Hidrojen", "Karbon"], a: "Hidrojen" },
        { q: "Dünyanın en eski tapınağı?", options: ["Piramitler", "Göbeklitepe", "Stonehenge", "Aztek"], a: "Göbeklitepe" },
        { q: "Kıta kayması teorisini kim buldu?", options: ["Darwin", "Wegener", "Newton", "Tesla"], a: "Wegener" },
        { q: "Magna Carta hangi kral döneminde imzalandı?", options: ["Arslan Yürekli Richard", "Yurtsuz John", "8. Henry", "1. Edward"], a: "Yurtsuz John" }
    ]
};
