const questionBank = {
    easy: [
        { q: "Türkiye'nin başkenti neresidir?", a: "ankara" },
        { q: "Gökkuşağı kaç renkten oluşur?", a: "7" },
        { q: "Dünyanın uydusu hangisidir?", a: "ay" },
        { q: "İstiklal Marşı'nın yazarı kimdir?", a: "mehmet akif ersoy" },
        { q: "Alfabemizin ilk harfi nedir?", a: "a" },
        { q: "Mıknatıs hangi metali çeker?", a: "demir" },
        { q: "Su kaç derecede donar?", a: "0" },
        { q: "Haftanın ilk günü hangisidir?", a: "pazartesi" },
        { q: "Üçgenin kaç köşesi vardır?", a: "3" },
        { q: "Güneş hangi yönden doğar?", a: "doğu" },
        { q: "Tavşanlar en çok hangi sebzeyi sever?", a: "havuç" },
        { q: "Kırmızı ve sarı karışınca hangi renk olur?", a: "turuncu" },
        { q: "Futbol maçları kaç dakika sürer?", a: "90" },
        { q: "Ekmek hangi tahıldan yapılır?", a: "buğday" },
        { q: "Pamuk Prenses kaç cüceyle yaşar?", a: "7" },
        { q: "Dört kere dört kaç eder?", a: "16" },
        { q: "Hangi hayvan 'hav hav' der?", a: "köpek" },
        { q: "En soğuk mevsim hangisidir?", a: "kış" },
        { q: "Gökyüzü gündüz hangi renktir?", a: "mavi" },
        { q: "Bal arıları ne üretir?", a: "bal" },
        { q: "Türkiyenin en kalabalık şehri?", a: "istanbul" },
        { q: "Zeytin dalı neyin sembolüdür?", a: "barış" },
        { q: "Sütün rengi nedir?", a: "beyaz" },
        { q: "Hangi gezegen halkalarıyla tanınır?", a: "satürn" },
        { q: "Karınca hangi hayvan grubundadır?", a: "böcek" },
        { q: "Ateşi kim bulmuştur?", a: "ilkel insan" },
        { q: "Atatürk kaç yılında doğdu?", a: "1881" },
        { q: "Bir gün kaç saattir?", a: "24" },
        { q: "Yaz mevsiminden sonra hangi mevsim gelir?", a: "sonbahar" },
        { q: "Tavuktan ne çıkar?", a: "yumurta" }
    ],
    medium: [
        { q: "Dünyanın en büyük okyanusu hangisidir?", a: "büyük okyanus" },
        { q: "Telefonu kim icat etti?", a: "graham bell" },
        { q: "Limonata yapımında kullanılan asit?", a: "sitrik asit" },
        { q: "Periyodik tabloda 'Au' hangi elementtir?", a: "altın" },
        { q: "Hücrenin enerji santrali neresidir?", a: "mitokondri" },
        { q: "İlk Türk astronot kimdir?", a: "alper gezeravcı" },
        { q: "Mona Lisa tablosu kime aittir?", a: "da vinci" },
        { q: "Sıvı haldeki tek metal hangisidir?", a: "cıva" },
        { q: "Işık hızı saniyede kaç bin km'dir?", a: "300" },
        { q: "Osmalı İmparatorluğu'nun ilk padişahı?", a: "osman bey" },
        { q: "Hangi ülke 'Yükselen Güneşin Ülkesi'dir?", a: "japonya" },
        { q: "Futbolda 'Altın Top' ödülünü en çok alan?", a: "messi" },
        { q: "Kuduz aşısını kim bulmuştur?", a: "louis pasteur" },
        { q: "Pusula iğnesi hangi yönü gösterir?", a: "kuzey" },
        { q: "Nobel ödülleri hangi ülkede verilir?", a: "isveç" },
        { q: "Türkiyenin en yüksek dağı?", a: "ağrı dağı" },
        { q: "Pi sayısının ilk üç basamağı?", a: "3.14" },
        { q: "Magna Carta hangi ülkede imzalandı?", a: "ingiltere" },
        { q: "En çok uydusu olan gezegen?", a: "satürn" },
        { q: "İnsan vücudundaki en sert yapı?", a: "diş minesi" },
        { q: "Dünyanın en uzun nehri?", a: "nil" },
        { q: "Satrancın ana vatanı neresidir?", a: "hindistan" },
        { q: "Kızıl Gezegen olarak bilinen gezegen?", a: "mars" },
        { q: "Sinekli Bakkal romanının yazarı?", a: "halide edip adıvar" },
        { q: "Yer çekimi kanununu kim buldu?", a: "newton" },
        { q: "Modern kimyanın babası kimdir?", a: "lavoisier" },
        { q: "Hangi organımız kanı pompalar?", a: "kalp" },
        { q: "Eyfel Kulesi hangi şehirdedir?", a: "paris" },
        { q: "Osmanlı'nın İstanbul'u fethettiği yıl?", a: "1453" },
        { q: "Piramitler hangi ülkededir?", a: "mısır" }
    ],
    hard: [
        { q: "Divan-ı Lügati't-Türk yazarı kimdir?", a: "kaşgarlı mahmut" },
        { q: "Dante'nin ünlü eserinin adı?", a: "ilahi komedya" },
        { q: "Hangi elementin simgesi 'W' harfidir?", a: "tungsten" },
        { q: "Modern atom teorisinin kurucusu?", a: "john dalton" },
        { q: "Dünyanın en derin noktası neresidir?", a: "mariana çukuru" },
        { q: "Ütopya kitabının yazarı kimdir?", a: "thomas more" },
        { q: "Karaciğerin kendini yenileme özelliği?", a: "rejenerasyon" },
        { q: "Görelilik teorisini kim ortaya attı?", a: "einstein" },
        { q: "İlk bilgisayarın adı nedir?", a: "eniac" },
        { q: "Kuantum mekaniğinin öncülerinden biri?", a: "max planck" },
        { q: "Makyavelizm düşüncesinin babası?", a: "machiavelli" },
        { q: "Ses hızını aşan ilk insan?", a: "chuck yeager" },
        { q: "İnsan DNA'sındaki baz çifti sayısı?", a: "3 milyar" },
        { q: "Oksijenin atom numarası kaçtır?", a: "8" },
        { q: "Asal sayıların en küçüğü kaçtır?", a: "2" },
        { q: "Yüzyıl Savaşları hangi devletler arasındaydı?", a: "ingiltere ve fransa" },
        { q: "Güneşin yüzey sıcaklığı yaklaşık kaç derecedir?", a: "5500" },
        { q: "Hangi element oda sıcaklığında gaz değildir?", a: "brom" },
        { q: "En fazla Nobel ödülü alan kadın bilim insanı?", a: "marie curie" },
        { q: "Dünyanın en küçük ülkesi hangisidir?", a: "vatikan" },
        { q: "Piri Reis'in ünlü haritası hangi yıla aittir?", a: "1513" },
        { q: "Sefiller romanının yazarı kimdir?", a: "victor hugo" },
        { q: "Elektrik akımı birimi nedir?", a: "amper" },
        { q: "Dünyanın en büyük adası hangisidir?", a: "grönland" },
        { q: "Bizans İmparatorluğu'nun diğer adı?", a: "doğu roma" },
        { q: "Rönesans'ın başladığı ülke?", a: "italya" },
        { q: "İnsan vücudundaki en küçük kemik?", a: "üzengi" },
        { q: "Güneş sistemindeki en soğuk gezegen?", a: "neptün" },
        { q: "I. Dünya Savaşı'nı bitiren antlaşma?", a: "versay" },
        { q: "Suç ve Ceza kitabının yazarı?", a: "dostoyevski" }
    ]
};