const questionBank = {
    easy: [
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },
        { q: "UMUTUN AŞIK OLDUĞU KIZIN ADI NEDİR", options: ["HAVVA", "ABDULREZZAK", "EBU CEHİL", "MUTTALİP"], a: "HAVVA" },        
        { q: "Futbol maçında bir takım kaç kişidir?", options: ["9", "10", "11", "12"], a: "11" }
    ],
    medium: [
        { q: "Telefonu kim icat etti?", options: ["Edison", "Graham Bell", "Tesla", "Newton"], a: "Graham Bell" },
        { q: "Mona Lisa tablosu kime aittir?", options: ["Picasso", "Da Vinci", "Dali", "Van Gogh"], a: "Da Vinci" },
        { q: "Hangi ülke 'Yükselen Güneşin Ülkesi'dir?", options: ["Çin", "Hindistan", "Japonya", "Kore"], a: "Japonya" },
        { q: "Kızıl Gezegen hangisidir?", options: ["Venüs", "Mars", "Jüpiter", "Satürn"], a: "Mars" },
        { q: "İnsan vücudundaki en büyük organ?", options: ["Beyin", "Akciğer", "Deri", "Karaciğer"], a: "Deri" },
        { q: "Osmalı İmparatorluğu'nun ilk padişahı?", options: ["1. Murat", "Orhan Bey", "Osman Bey", "Fatih"], a: "Osman Bey" },
        { q: "Sıvı haldeki tek metal hangisidir?", options: ["Demir", "Bakır", "Altın", "Cıva"], a: "Cıva" },
        { q: "Titanic hangi yıl battı?", options: ["1910", "1912", "1915", "1920"], a: "1912" },
        { q: "Dünyanın en uzun nehri hangisidir?", options: ["Amazon", "Nil", "Fırat", "Ganj"], a: "Nil" },
        { q: "Sinekli Bakkal romanının yazarı?", options: ["Ziya Gökalp", "H. Edip Adıvar", "Yaşar Kemal", "Orhan Pamuk"], a: "H. Edip Adıvar" },
        { q: "Periyodik tabloda 'Au' simgesi nedir?", options: ["Gümüş", "Bakır", "Altın", "Alüminyum"], a: "Altın" },
        { q: "Kuduz aşısını kim bulmuştur?", options: ["Pasteur", "Fleming", "Curie", "Edison"], a: "Pasteur" },
        { q: "Türkiye'nin en yüksek dağı?", options: ["Erciyes", "Nemrut", "Ağrı", "Süphan"], a: "Ağrı" },
        { q: "Pi sayısının yaklaşık değeri kaçtır?", options: ["2.14", "3.14", "4.14", "5.14"], a: "3.14" },
        { q: "Matbaayı kim icat etti?", options: ["Gutenberg", "Galileo", "Da Vinci", "Watt"], a: "Gutenberg" },
        { q: "Eyfel Kulesi nerededir?", options: ["Roma", "Londra", "Paris", "Berlin"], a: "Paris" },
        { q: "En çok uydusu olan gezegen hangisidir?", options: ["Mars", "Jüpiter", "Satürn", "Uranüs"], a: "Satürn" },
        { q: "Satrancın ana vatanı neresidir?", options: ["Çin", "Yunanistan", "Hindistan", "Mısır"], a: "Hindistan" },
        { q: "Fatih Sultan Mehmet kaç yaşında İstanbul'u fethetti?", options: ["19", "21", "23", "25"], a: "21" },
        { q: "Hangi vitamin güneş ışığıyla alınır?", options: ["A", "B", "C", "D"], a: "D" }
    ],
    hard: [
        { q: "Asal sayıların en küçüğü kaçtır?", options: ["0", "1", "2", "3"], a: "2" },
        { q: "Sefiller romanının yazarı kimdir?", options: ["Hugo", "Dostoyevski", "Tolstoy", "Balzac"], a: "Hugo" },
        { q: "Hangi elementin simgesi 'W' harfidir?", options: ["Varyum", "Tungsten", "Gümüş", "Cıva"], a: "Tungsten" },
        { q: "Dünyanın en derin noktası neresidir?", options: ["Mariana Çukuru", "Everest", "Bermuda", "Nil"], a: "Mariana Çukuru" },
        { q: "Ütopya kitabının yazarı kimdir?", options: ["Platon", "Machiavelli", "Thomas More", "Hegel"], a: "Thomas More" },
        { q: "Karaciğerin kendini yenileme özelliği?", options: ["Metamorfoz", "Rejenerasyon", "Fagositoz", "Osmoz"], a: "Rejenerasyon" },
        { q: "Modern atom teorisinin kurucusu?", options: ["Bohr", "Dalton", "Einstein", "Planck"], a: "Dalton" },
        { q: "Dante'nin ünlü eserinin adı?", options: ["Suç ve Ceza", "İlahi Komedya", "Don Kişot", "Faust"], a: "İlahi Komedya" },
        { q: "Nobel ödülleri hangi ülkede verilir?", options: ["Almanya", "İsveç", "ABD", "İsviçre"], a: "İsveç" },
        { q: "Elementlerin periyodik tablosunu kim oluşturdu?", options: ["Mendeleyev", "Nobel", "Curie", "Darwin"], a: "Mendeleyev" },
        { q: "Oksijenin atom numarası kaçtır?", options: ["6", "7", "8", "9"], a: "8" },
        { q: "Hangi gezegen ters yönde döner?", options: ["Mars", "Venüs", "Jüpiter", "Neptün"], a: "Venüs" },
        { q: "Genetik biliminin kurucusu kimdir?", options: ["Darwin", "Lamarck", "Mendel", "Watson"], a: "Mendel" },
        { q: "İnsan vücudundaki en küçük kemik?", options: ["Üzengi", "Çekiç", "Örs", "Kaval"], a: "Üzengi" },
        { q: "Don Kişot'un yazarı kimdir?", options: ["Cervantes", "Lorca", "Hugo", "Moliere"], a: "Cervantes" },
        { q: "Altın oran rakamı kaçtır?", options: ["1.414", "1.618", "2.718", "3.141"], a: "1.618" },
        { q: "Aspirinin ham maddesi hangi ağaçtır?", options: ["Meşe", "Çam", "Söğüt", "Gürgen"], a: "Söğüt" },
        { q: "Nobel Barış Ödülü hangi şehirde verilir?", options: ["Stokholm", "Oslo", "Kopenhag", "Helsinki"], a: "Oslo" },
        { q: "I. Dünya Savaşı'nı bitiren antlaşma?", options: ["Lozan", "Mondros", "Versay", "Sevr"], a: "Versay" },
        { q: "İnsan kalbi günde yaklaşık kaç kez atar?", options: ["50 bin", "75 bin", "100 bin", "150 bin"], a: "100 bin" }
    ]
};

